### ISSUE TITLE
SkyLeach/pudb.vim cannot use , only import pudb; pu.db is useful.

### ISSUE THREAD

**Issue by forgethub** [hwalinga/django-pudb3#2]
SkyLeach/pudb.vim cannot use , only import pudb; pu.db is useful.

**Comment by hwalinga** [comment]
That is not the intent of this middleware. The only thing it does is to intercept interceptions and put you in pudb when it happens, so that you can do post-mortem debugging. You can use `import pudb; pu.db` without this package. From the documentation of pudb.vim it seems you probably have to set `pudb_entry_point` to your `manage.py`. This might also interest you: https://github.com/0atman/django-pdb-pudb if it still works.
